<a href="https://colab.research.google.com/github/KShikha19/PY/blob/main/fitbit_analysis_numpy3_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!gdown 1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd


Downloading...
From: https://drive.google.com/uc?id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd
To: /content/fit.txt
100% 3.43k/3.43k [00:00<00:00, 11.9MB/s]


In [2]:
import numpy as np
data = np.loadtxt('fit.txt', dtype = str)
data


<ipython-input-2-639bb6db62b8>:2: UserWarning: Input line 1 contained no data and will not be counted towards `max_rows=50000`.  This differs from the behaviour in NumPy <=1.22 which counted lines rather than rows.  If desired, the previous behaviour can be achieved by using `itertools.islice`.
Please see the 1.23 release notes for an example on how to do this.  If you wish to ignore this warning, use `warnings.filterwarnings`.  This warning is expected to be removed in the future and is given only once per `loadtxt` call.
  data = np.loadtxt('fit.txt', dtype = str)


array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [3]:
data.shape

(96, 6)

In [4]:
data.ndim

2

In [5]:
data.T.shape

(6, 96)

In [6]:
date,step_count,mood,calories_burned,hours_of_sleep,activity = data.T

In [7]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [9]:
step_count = np.array(step_count, dtype = int)
hours_of_sleep = np.array(hours_of_sleep,dtype=int)
calories_burned = np.array(calories_burned,dtype=int)

In [12]:
#avg step_count
np.mean(step_count)

np.float64(2935.9375)

In [13]:
#day my step count is highest
np.max(step_count)

np.int64(7422)

In [15]:
np.argmax(step_count)

np.int64(69)

In [16]:
date[np.argmax(step_count)]

np.str_('14-12-2017')

In [17]:
date[step_count == max(step_count)]

array(['14-12-2017'], dtype='<U10')

In [18]:
#avg step count when mood is happy
step_count[mood == 'Happy']

array([4732,  330, 4550, 4435, 4779, 1831, 2255,  539, 5464, 4068, 4683,
       4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  269, 4275, 5999,
       4421, 6930, 5195,  546,  493,  995, 3608,  774, 1421, 4064, 2725,
       5934, 1867, 7422, 5537, 5376,  153, 2203])

In [20]:
np.mean(step_count[mood == 'Happy'])

np.float64(3392.725)

In [22]:
#avg step count when mood is sad
np.mean(step_count[mood == 'Sad'])

np.float64(2103.0689655172414)

In [25]:
#avg step count when my mood is either sad or neutral

(mood == 'Sad') | (mood == 'Neutral')

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False,  True,
        True, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False])

In [26]:
step_count[(mood == 'Sad') | (mood == 'Neutral')]

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,  292,
       2209, 6041,  570, 1163, 6676, 3721, 2374, 2909, 1648,  799, 7102,
       3941,  437, 1231, 1696, 4921,  221, 6500, 3575, 4061,  651,  753,
        518, 4108, 3066,  177,   36,  299, 1447, 2599,  702,  133,  500,
       2127])

In [27]:
np.mean(step_count[(mood == 'Sad') | (mood == 'Neutral')])

np.float64(2609.660714285714)

In [28]:
hours_of_sleep

array([5, 8, 5, 4, 5, 6, 6, 7, 5, 6, 8, 5, 6, 7, 5, 6, 8, 5, 4, 5, 6, 8,
       5, 6, 5, 8, 5, 4, 5, 4, 5, 4, 3, 2, 9, 5, 6, 4, 5, 8, 4, 5, 6, 5,
       6, 5, 6, 5, 6, 5, 6, 7, 6, 7, 6, 5, 6, 7, 8, 8, 7, 8, 5, 4, 3, 3,
       4, 5, 5, 5, 3, 4, 4, 5, 5, 5, 5, 5, 5, 4, 3, 4, 5, 5, 4, 5, 3, 3,
       3, 2, 3, 2, 8, 5, 5, 5])

In [29]:
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [32]:
#avg hours of sleep when mood is happy
np.mean(hours_of_sleep[mood == 'Happy'])

np.float64(5.725)

In [33]:
#avg hours of sleep when mood is sad
np.mean(hours_of_sleep[mood == 'Sad'])

np.float64(5.0344827586206895)

In [34]:
#avg hours of sleep when mood is Neutral
np.mean(hours_of_sleep[mood == 'Neutral'])

np.float64(4.666666666666667)

In [35]:
# On how many days did step count more than 10,000 steps?
np.sum(step_count > 10000)

np.int64(0)

In [38]:
#3. How many days did hours of sleep less than 6 ?
np.sum(hours_of_sleep < 6)


np.int64(63)

In [39]:
len(hours_of_sleep)

96

In [40]:
#. What is the highest number of calories burned in a day?
np.max(calories_burned)

np.int64(243)

In [42]:
 #On which date did  the most calories were burned?
 date[np.argmax(calories_burned)]

np.str_('14-12-2017')

In [43]:
#. What is the range (max - min) of step count values?
np.max(step_count) - np.min(step_count)

np.int64(7397)