<a href="https://colab.research.google.com/github/KShikha19/PY/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
a = [1,2,3,4,5]
type(a)

list

In [ ]:
a

[1, 2, 3, 4, 5]

In [ ]:
#square each element of my list
res = [i**2 for i in a]
res

[1, 4, 9, 16, 25]

In [ ]:
#define the numpy array
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
#concise
a**2

array([ 1,  4,  9, 16, 25])

In [ ]:
#which on is faster
l = range(1000000)
%timeit [i**2 for i in l]

90.4 ms ± 19.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
a = np.array(range(1000000))
%timeit a**2

702 µs ± 42.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
#dimensions and shape

In [ ]:
arr1 = np.array(range(1000))
arr1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [ ]:
arr1.ndim #dimensions of a array

1

In [ ]:
arr2 = np.array(range(10))
print(arr2)
print(arr2.ndim)

[0 1 2 3 4 5 6 7 8 9]
1


In [ ]:
arr1.shape #number of elements in evry dimensions => output of shape => tuple

(1000,)

In [ ]:
arr2.shape

(10,)

In [ ]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr3.ndim

2

In [ ]:
arr3.shape

(2, 3)

In [ ]:
#quiz
#What will be the output of the following code?
a = np.array([1,2,3,4,5,6,7,8])
print(a.ndim, a.shape)

1 (8,)


In [ ]:
#np.arange()

In [ ]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [ ]:
list(range(1,10,0.5))

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
arr2 = np.arange(1,5)
arr2

array([1, 2, 3, 4])

In [ ]:
arr2 = np.arange(2,5,0.5)
arr2

array([2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
arr2 = np.arange(1,10,2)
arr2

array([1, 3, 5, 7, 9])

In [ ]:
arr2 = np.arange(1,10,2.5)
arr2

array([1. , 3.5, 6. , 8.5])

In [ ]:
arr = np.array([1,2,3,4.0])
arr

array([1., 2., 3., 4.])

In [ ]:
#str > float >int
arr = np.array(['priyesh',2,3,4.5])
arr

array(['priyesh', '2', '3', '4.5'], dtype='<U32')

In [ ]:
int(6.7)

6

In [ ]:
round(6.7)

7

In [ ]:
arr = np.array([1,2,3,6.7],dtype = 'int')
arr

array([1, 2, 3, 6])

In [ ]:
arr = np.array([2,3,4.5,'a','b'],dtype='int')
arr

ValueError: invalid literal for int() with base 10: 'a'

In [ ]:
int(4.5)

4

In [ ]:
int('1')

1

In [ ]:
arr = np.array([2,3,4.5,'1','2'],dtype='int')
arr

array([2, 3, 4, 1, 2])

In [ ]:
arr = np.array([2,3,4.5])
arr.astype('int')

array([2, 3, 4])

In [ ]:
arr.astype('float')

array([2. , 3. , 4.5])

In [ ]:
arr = np.array([2,3,4.5,'1','2.5'],dtype='int') #explore it  #homework
arr

ValueError: invalid literal for int() with base 10: '2.5'

In [ ]:
int('1')

1

In [ ]:
int('2.5')

ValueError: invalid literal for int() with base 10: '2.5'

In [ ]:
int(float('2.5'))

2

In [ ]:
int(input())

2.5


ValueError: invalid literal for int() with base 10: '2.5'

In [ ]:
arr3 = np.array([1,2,3,4,5,6.7],dtype='int')
arr3

array([1, 2, 3, 4, 5, 6])

In [ ]:
#indexing
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr[0]

np.int64(0)

In [ ]:
arr[6]

np.int64(6)

In [ ]:
arr[-3]

np.int64(9)

In [ ]:
arr[[2,7,-2]] #multiple indexes

array([ 2,  7, 10])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr[0]

np.int64(0)

In [ ]:
arr[-1]

np.int64(11)

In [ ]:
arr[2]

np.int64(2)

In [ ]:
arr[[0,-1,2]]

array([ 0, 11,  2])

In [ ]:
#slicing
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr[0:5] #first 5 elements

array([0, 1, 2, 3, 4])

In [ ]:
arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[-5:-1]

array([ 7,  8,  9, 10])

In [ ]:
arr[2:10:2]

array([2, 4, 6, 8])

In [ ]:
arr[-5:-8]

array([], dtype=int64)

In [ ]:
arr[-5:-8:-1]

array([7, 6, 5])

In [ ]:
#What will be the output of the following code?
import numpy as np
a = np.array([0,1,2,3,4,5])
a[4:] = 10
print(a)

[ 0  1  2  3 10 10]


In [ ]:
#fancy indexing(masking)

In [ ]:
arr = np.array([10,5,6,1,1,2,10,15,7,8])
arr

array([10,  5,  6,  1,  1,  2, 10, 15,  7,  8])

In [ ]:
arr < 6

array([False,  True, False,  True,  True,  True, False, False, False,
       False])

In [ ]:
arr[arr<6]

array([5, 1, 1, 2])

In [ ]:
arr[arr%2 == 0]

array([10,  6,  2, 10,  8])